Repository danger/danger-js, pull requests merged in 2020-03, with the labels that each got.

#1011 Fix "@octokit/rest" deprecation warning when using ".issues.addLabels()"
  CHANGELOG.md
  source/platforms/github/GitHubUtils.ts
Labels: Merge On Green

#1013 Fix GitHub Actions condition
  CHANGELOG.md
  source/ci_source/providers/GitHubActions.ts
  source/platforms/github/GitHubAPI.ts
Labels: bug

#1002 Add structured diff support to Gitlab
  CHANGELOG.md
  source/dsl/GitLabDSL.ts
  source/platforms/_tests/fixtures/gitlab_mr.json
  source/platforms/gitlab/GitLabAPI.ts
  source/platforms/gitlab/GitLabGit.ts
  source/platforms/gitlab/_tests/__snapshots__/_gitlab_git.test.ts.snap
  source/platforms/gitlab/_tests/_gitlab_api.test.ts
  source/platforms/gitlab/_tests/_gitlab_git.test.ts
  source/platforms/gitlab/_tests/fixtures/fileContentsAfter.txt
  source/platforms/gitlab/_tests/fixtures/fileContentsBefore.txt
  source/platforms/gitlab/_tests/fixtures/getCompareChanges.json
  source/platforms/gitlab/_tests/fixtures/getMergeRequestChanges.json
  source/platforms/gitlab/_tests/fixtures/getMergeRequestCommits.json
  source/platforms/gitlab/_tests/fixtures/getMergeRequestInfo.json
  source/platforms/gitlab/_tests/fixtures/getMergeRequestInlineNotes.json
  source/platforms/gitlab/_tests/fixtures/getMergeRequestNotes.json
  source/platforms/gitlab/_tests/fixtures/gitlab_changes.json
  source/runner/jsonToDSL.ts
Labels: enhancement
