Repository danger/danger-js, pull requests merged in 2020-02, with the labels that each got.

#996 Fix import in template script
  package.json
  scripts/danger-dts.ts
  yarn.lock
Labels: bug

#1000 Minor docs improvement for GitHub Actions
  source/ci_source/providers/GitHubActions.ts
Labels: enhancement

#998 Fix repository slug in Jenkins provider
  CHANGELOG.md
  source/ci_source/providers/Jenkins.ts
Labels: Merge On Green
